### ISSUE TITLE
Cannot find module React

### ISSUE THREAD

**Issue by roccomuso** [dfrankland/hyperterm-tab-icons#14]
I've added `hyperterm-tab-icons` or `hyper-tab-icons` to the plugins. And i got this error:

> failed to load (Cannot find module 'React')

**Comment by dfrankland** [comment]
What version of Hyper.app are you using and what version of `hyper-tab-icons` are you using?

**Comment by anirudhb** [comment]
I've got the same error

**Comment by anirudhb** [comment]
Hyper 0.8.3 and git-HEAD version of `hyper-tab-icons`.

**Comment by anirudhb** [comment]
Just found a way to suppress the error: `npm install react` in `.hyper_plugins` and in `index.js`, change the capital R in `require("React")` to a lowercase R. A white icon shows up, at least.

**Comment by anirudhb** [comment]
Oh! I'm using `hyperterm-mactabs` which makes the icon invisible. I removed it, and IT WORKS!
I might submit a pull request to invert white if using `hyperterm-mactabs`.

**Comment by anirudhb** [comment]
Yes! I figured out how to make it work with `hyperterm-mactabs`!
🎉

**Comment by anirudhb** [comment]
Fixing some bugs... 😅

**Comment by anirudhb** [comment]
@dfrankland Hello?

**Comment by dfrankland** [comment]
> Just found a way to suppress the error: npm install react in .hyper_plugins and in index.js, change the capital R in require("React") to a lowercase R. A white icon shows up, at least.

Good catch, I will update this ASAP.

**Comment by dfrankland** [comment]
Should be fixed with this release: https://github.com/dfrankland/hyper-tab-icons/releases/tag/v1.1.2

Would y'all, @roccomuso & @anirudhb, be able to test?

**Comment by anirudhb** [comment]
I already did that patch on my local machine (and a few others) and I can say, 👍

**Comment by anirudhb** [comment]
Just redownloaded

**Comment by anirudhb** [comment]
👍
