### ISSUE TITLE
mapIcons mappings don't apply colors from mapColors

### ISSUE THREAD

**Issue by mattdarveniza** [dfrankland/hyperterm-tab-icons#20]
I've got a mapIcon config that maps a few python-based commands (pyramid specifically) to the python icon, however I've noticed that this mapping doesn't pick up the color specified for the python color mapping. For example:

```javascript
{
  mapColors: {
    python: 'hsl(39, 67%, 69%)',
  },
  mapIcons: {
    python: ['pserve']
  }
}
```

This config will apply the icon, but not the color to any `pserve` commands. Putting `pserve` into the mapColors config fixes, but it would be nice if it picked up the base icon's color if no custom one was specified.

**Comment by dfrankland** [comment]
Sorry about this issue. This should be fixed in `hyper-tab-icons@1.1.5` with this commit: https://github.com/dfrankland/hyper-tab-icons/commit/649c4092be538aad0a41e8f9d0def69126b776dc
