### ISSUE TITLE
Please update in npm

### ISSUE THREAD

**Issue by andretf** [dfrankland/hyperterm-tab-icons#26]
The plugin is not at the latest version in npm repository to reflect last fixes.
Just adding 'hyperterm-tab-icons' to .hyper.js/plugins throws error described in #14.

**Comment by dfrankland** [comment]
That fix was released last year in December, and the last time I released this package was 2 weeks ago.

[Check the npm page](https://www.npmjs.com/package/hyper-tab-icons) and you can easily see that `react` is listed as a dependency. Also you can run `npm info hyper-tab-icons` and see that the `dependencies` include `react`.

Can you check that you have the latest version installed, and that you are indeed using `hyper-tab-icons` and not `hyperterm-tab-icons`?

**Comment by andretf** [comment]
Thank you, I was using wrong repository. `bnb/awesome-hyper` still lists plugin as `hyperterm-tab-icons`.
May I suggest you to point current npm repository in Readme, it would be clearer.
