### ISSUE TITLE
Cannot find module React

### ISSUE THREAD

**Issue by yonilerner** [dfrankland/hyperterm-tab-icons#27]
![image](https://user-images.githubusercontent.com/278810/28655806-003ad258-7253-11e7-9bbc-fd12aba4c48f.png)

**Comment by dfrankland** [comment]
This was solved a while ago:
https://github.com/dfrankland/hyper-tab-icons/issues/14
https://github.com/dfrankland/hyper-tab-icons/issues/26

**Comment by yonilerner** [comment]
I installed it for the first time ever last night. Is that fix not published to npm?

**Comment by dfrankland** [comment]
Please install `hyper-tab-icons` 👍  `hyperterm-tab-icons` was deprecated.

**Comment by yonilerner** [comment]
Works like magic. Thanks!
