### ISSUE TITLE
Interactions with pure prompt / zsh

### ISSUE THREAD

**Issue by nhejazi** [dfrankland/hyperterm-tab-icons#32]
I just found this plug-in and have run into an error in trying to use it. As best as I can tell, it appears that the plugin functions as intended but that what it writes to the tab in a hyper session is quickly overwritten (e.g., when I start a new tab with zsh, the standard shell icon appears, and, when I then start python, the python icon appears for a split second before being overwritten again by the shell icon).

Has anyone else experienced such an issue? Any help would be much appreciated. Thanks in advance.

In case it helps, I am using the [pure prompt for zsh](https://github.com/sindresorhus/pure), and here are links to my `zshrc` and `hyper.js` below:

`hyper.js`: https://github.com/nhejazi/mydotfiles/blob/master/hyper.js
`zshrc`: https://github.com/nhejazi/mydotfiles/blob/master/zshrc

**Comment by dfrankland** [comment]
I am pretty sure this is either a misconfiguration in your `zshrc` or you need configure [`processNameRegex `](https://github.com/dfrankland/hyper-tab-icons#configtabiconsprocessnameregex).
