### ISSUE TITLE
Not Working/Changing

### ISSUE THREAD

**Issue by nmsmith22389** [dfrankland/hyperterm-tab-icons#33]
I tried on stable and canary. The initial default icon pops up but it never changes.

macOS High Sierra

**Comment by dfrankland** [comment]
Are you using bash?

**Comment by sangdth** [comment]
I have same issue, the first icon shows up but never change, even when I use `mapIcons`.

And when I echo bash, it showed `/usr/local/bin/bash`, should I do anything extra to get it works? 

Thanks.

**Comment by RoyHP** [comment]
Is this not expected to work in zsh? (because it doesn't for me) - icon also stays as the terminal icon. Using zsh on high sierra with node 8.

**Comment by sangdth** [comment]
Dear @dfrankland , do I really need to map the icons manually in order to make it works?

**Comment by sangdth** [comment]
I don't know why, but I added this block into bash_profile, and it works!

https://github.com/zeit/hyper/issues/1188#issuecomment-267301723

If I could have some explaination, it would be great as I'm still learning programming. I don't want just copy/paste. Thanks for your time, much appreciate.

**Comment by dfrankland** [comment]
@RoyHP & @sangdth - Bash and Zsh do not change the title out of the box. You must configure them to actually change the title. `hyper-tab-icons` will change the icon depending on the text of the title. If you check the link that @sangdth added (https://github.com/zeit/hyper/issues/1188#issuecomment-267301723), it's a thread on [`hyper`](https://github.com/zeit/hyper) about how to set the title.

**Comment by sangdth** [comment]
Thank you @dfrankland !

**Comment by bmrobin** [comment]
@sangdth confirmed, that bash_profile worked for me as well. i think this issue can be marked as resolved since there is a work-around
